name: node.js test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run-server:
    runs-on: ubuntu-latest
    steps:

      - name: build-and-execute-server+test
        run: |
          ls -la
          npm install
          npm test
